# Form implementation generated from reading ui file 'createProfile.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_createProfileDialog(object):
    def setupUi(self, createProfileDialog):
        createProfileDialog.setObjectName("createProfileDialog")
        createProfileDialog.resize(600, 345)
        createProfileDialog.setMinimumSize(QtCore.QSize(600, 345))
        createProfileDialog.setMaximumSize(QtCore.QSize(600, 345))
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=createProfileDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 300, 581, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(30)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.cancelButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.confirmButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout.addWidget(self.confirmButton)
        self.descriptionInput = QtWidgets.QTextEdit(parent=createProfileDialog)
        self.descriptionInput.setGeometry(QtCore.QRect(10, 40, 571, 221))
        self.descriptionInput.setObjectName("descriptionInput")
        self.profileLabel = QtWidgets.QLabel(parent=createProfileDialog)
        self.profileLabel.setGeometry(QtCore.QRect(10, 280, 111, 16))
        self.profileLabel.setObjectName("profileLabel")
        self.descriptionLabel = QtWidgets.QLabel(parent=createProfileDialog)
        self.descriptionLabel.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.descriptionLabel.setObjectName("descriptionLabel")

        self.retranslateUi(createProfileDialog)
        QtCore.QMetaObject.connectSlotsByName(createProfileDialog)

    def retranslateUi(self, createProfileDialog):
        _translate = QtCore.QCoreApplication.translate
        createProfileDialog.setWindowTitle(_translate("createProfileDialog", "Dialog"))
        self.cancelButton.setText(_translate("createProfileDialog", "Confirm"))
        self.confirmButton.setText(_translate("createProfileDialog", "Cancel"))
        self.profileLabel.setText(_translate("createProfileDialog", "Input Profile Name"))
        self.descriptionLabel.setText(_translate("createProfileDialog", "Profile Description"))
